name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        experimental: [false]

        include:
          - os: ubuntu-latest
            python-version: "2.7"
            experimental: true
          - os: macos-latest
            python-version: "2.7"
            experimental: true
          - os: windows-latest
            python-version: "2.7"
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows' && matrix.python-version == '2.7'
        run: |
          choco install vcpython27 -f -y

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython
          python -m pip install pytest
          python -m pip install "numpy<1.17;python_version<'3.4'" "numpy<1.22;python_version=='3.7'" "numpy;python_version>'3.7'"

      - name: Test the lib
        run: |
          python setup.py build_ext --inplace --force
          python setup.py check
          pytest .
